# syntax=docker/dockerfile:1

ARG NODE_VERSION=20
ARG SERVER_PORT=3001

FROM node:${NODE_VERSION}-bookworm AS base
WORKDIR /app

FROM base AS builder

COPY package.json yarn.lock lerna.json ./
COPY packages/client/package.json ./packages/client/
COPY packages/server/package.json ./packages/server/

RUN --mount=type=cache,target=/usr/local/share/.cache/yarn \
    yarn install --frozen-lockfile --network-timeout 600000

COPY . .

RUN yarn build --scope=server

FROM node:${NODE_VERSION}-bookworm-slim AS production
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/packages/server/dist/ ./
COPY --from=builder /app/packages/server/package.json ./package.json
COPY --from=builder /app/packages/server/.sequelizerc ./.sequelizerc
COPY --from=builder /app/packages/server/docker-entrypoint.sh ./docker-entrypoint.sh
COPY --from=builder /app/yarn.lock ./yarn.lock

RUN --mount=type=cache,target=/usr/local/share/.cache/yarn \
    yarn install --production=true --network-timeout 600000 \
    && chmod +x /app/docker-entrypoint.sh

ARG SERVER_PORT=3001
EXPOSE $SERVER_PORT
ENTRYPOINT ["/app/docker-entrypoint.sh"]
