ARG NODE_VERSION=20
ARG CLIENT_PORT=3001
ARG EXTERNAL_SERVER_URL
ARG INTERNAL_SERVER_URL

FROM node:$NODE_VERSION-bookworm AS base

WORKDIR /app

FROM base AS builder

ARG EXTERNAL_SERVER_URL
ARG INTERNAL_SERVER_URL
ENV EXTERNAL_SERVER_URL=$EXTERNAL_SERVER_URL \
    INTERNAL_SERVER_URL=$INTERNAL_SERVER_URL

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

FROM node:$NODE_VERSION-bookworm-slim AS production
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/packages/client/dist/ /app/dist/
COPY --from=builder /app/packages/client/server/ /app/server/
COPY --from=builder /app/packages/client/package.json /app/package.json
COPY --from=builder /app/yarn.lock /app/yarn.lock
RUN yarn install --production=true

EXPOSE $CLIENT_PORT
CMD [ "node", "/app/server/index.js" ]
